name='Doney'
age=22
cgpa=8.3
graduation_year=2026
profile=[name,age,cgpa,graduation_year]
print(profile)
print(len(profile))
#
profile.append('Pala')
profile.insert(1,'insert')
b=profile.copy()
print(b)
profile.pop(2)
profile.extend(b)
profile.reverse()
print(profile)
print(profile.count('Doney'))
a=[5,2,7]
print(a.sort())